version: "3.8"

services:
  app:
    command: npm run dev
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "${PORT}:${PORT}"

  db-tenants:
    ports:
      - "${DB_EXTERNAL_PORT}:5432"
